#!/bin/bash
set -euo pipefail

# DevHub Portless Mode Installer
# This script sets up Caddy as a reverse proxy on port 80
# so you can access projects via http://myapp.localhost (no port).
#
# Requires: Caddy installed (brew install caddy), sudo privileges.

DEVHUB_PORT="${DEVHUB_PROXY_PORT:-4400}"
BASE_DOMAIN="${DEVHUB_BASE_DOMAIN:-localhost}"
CADDYFILE="/usr/local/etc/devhub-Caddyfile"
PLIST="/Library/LaunchDaemons/com.devhub.caddy.plist"

echo "=== DevHub Portless Mode Setup ==="
echo ""
echo "This will:"
echo "  1. Write a Caddyfile to ${CADDYFILE}"
echo "  2. Create a LaunchDaemon to run Caddy on port 80"
echo ""
echo "DevHub proxy port: ${DEVHUB_PORT}"
echo "Base domain: ${BASE_DOMAIN}"
echo ""

# Check Caddy is installed
if ! command -v caddy &>/dev/null; then
  echo "ERROR: Caddy is not installed. Install it with: brew install caddy"
  exit 1
fi

# Generate Caddyfile
cat > "${CADDYFILE}" <<EOF
# DevHub Portless Proxy - Generated by install-portless.sh
# Routes all *.${BASE_DOMAIN} traffic to DevHub's internal proxy.

*.${BASE_DOMAIN}, ${BASE_DOMAIN} {
  reverse_proxy 127.0.0.1:${DEVHUB_PORT}
}
EOF

echo "Wrote Caddyfile to ${CADDYFILE}"

# Create LaunchDaemon plist
cat > "${PLIST}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.devhub.caddy</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(which caddy)</string>
    <string>run</string>
    <string>--config</string>
    <string>${CADDYFILE}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/var/log/devhub-caddy.log</string>
  <key>StandardErrorPath</key>
  <string>/var/log/devhub-caddy.log</string>
</dict>
</plist>
EOF

echo "Wrote LaunchDaemon to ${PLIST}"

# Load the daemon
launchctl load "${PLIST}" 2>/dev/null || true
launchctl start com.devhub.caddy 2>/dev/null || true

echo ""
echo "Done! Portless mode is now active."
echo "Access DevHub at: http://devhub.${BASE_DOMAIN}"
echo "Projects at: http://<slug>.${BASE_DOMAIN}"
